[![Build Status](https://travis-ci.org/github.com/peter1king/hello-world.svg?branch=master)](https://travis-ci.org/github.com/peter1king/hello-world)
[![GitHub license](https://img.shields.io/github/license/mashape/apistatus.svg)](https://github.com/peter1king/hello-world/blob/master/LICENCE)
